### ISSUE TITLE
Adding a Github action for mark

### ISSUE THREAD

**Issue by bhayes-zd** [kovetskiy/mark#46]
Hey there 👋  Love this project, so thank you for all that you do. Saves a lot of headache.

I think it could be really powerful to add direct support to run mark as a Github action via docker action. I've gone ahead and drafted up what that would look like below. Let me know if you'd like me to open a pull request!

```yaml
# action.yml
name: 'mark'
description: 'Tool for updating Atlassian Confluence pages from markdown.'
branding:
    icon: 'book-open'
    color: 'blue'
inputs:
    commands:
        user: 
            description: 'The confluence user account'
            required: true
            default: ${{ .Env.MARK_PASS }}
        pass:
            description: 'The confluence account password'
            required: true
            default: ${{ .Env.MARK_PASS }}
        url:
            description: 'The url of the confluence account'
            required: true
            default: ${{ .Env.MARK_URL }}
    options:
       description: 'The arguments to run'
       required: false
       default: '--debug'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - -u "${{ inputs.commands.user }}" -p "${{inputs.commands.pass}}" -b "${{inputs.commands.url}}" ${{inputs.options}}
```

```dockerfile
# Dockerfile

# Container image that runs your code
FROM golang:1.15

RUN go get github.com/kovetskiy/mark

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]
```

```shell
# entrypoint.sh

#!/bin/sh -l

$GOPATH/bin/kovetskiy/mark $1 $2
```
